### ISSUE TITLE
Scrollbar Issue

### ISSUE THREAD

**Issue by fahadchy24** [LaravelDaily/Laravel-Soft-UI-Bootstrap5-QuickAdminPanel#1]
Scrollbar issue appeared after cloning this repo. Can anyone give me a solution for this please? Thanks

![Screenshot_1](https://user-images.githubusercontent.com/28273983/127342484-47c93a74-a39f-4c18-a6d5-7718322f199e.png)
![Screenshot_2](https://user-images.githubusercontent.com/28273983/127342491-8a670ff8-f7ee-412b-b1f7-1a3655a158c5.png)

**Comment by fahadchy24** [comment]
Issue fixed by adding perfectscrollbar plugins cdn.

**Comment by rifqiadityariadhi** [comment]
Login Issue, can u give me solution?

<img width="1274" alt="Screen Shot 2021-12-05 at 16 23 40" src="https://user-images.githubusercontent.com/33438628/144739225-718b676d-4563-4894-b31e-4055eabdb541.png">

**Comment by mainadennis** [comment]
That means you do not have a csrf field in your file. Try adding
***@***.***_field` or `{{method_field('POST')}}` just below the html form
attribute
